// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ShibAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240808134755_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("System_NFT_Attribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayType")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "display_type");

                    b.Property<int?>("MetadataId")
                        .HasColumnType("integer");

                    b.Property<int?>("System_NFT_MetadataId")
                        .HasColumnType("integer");

                    b.Property<string>("TraitType")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "trait_type");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "value");

                    b.HasKey("Id");

                    b.HasIndex("System_NFT_MetadataId");

                    b.ToTable("NftAttribute");

                    b.HasAnnotation("Relational:JsonPropertyName", "attributes");
                });

            modelBuilder.Entity("System_NFT_Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AnimationUrl")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "animation_url");

                    b.Property<string>("ExternalAppUrl")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "external_app_url");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "image_url");

                    b.Property<bool?>("IsUnique")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "is_unique");

                    b.Property<int?>("MetadataId")
                        .HasColumnType("integer");

                    b.Property<string>("NFT_Id")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("Owner")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "owner");

                    b.Property<string>("SerializedAttributes")
                        .HasColumnType("text");

                    b.Property<string>("SerializedItems")
                        .HasColumnType("text");

                    b.Property<int?>("TokenId")
                        .HasColumnType("integer");

                    b.Property<string>("TokenType")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "token_type");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "value");

                    b.HasKey("Id");

                    b.HasIndex("MetadataId");

                    b.HasIndex("TokenId");

                    b.ToTable("NftItem");
                });

            modelBuilder.Entity("System_NFT_Metadata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "description");

                    b.Property<string>("ExternalUrl")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "external_url");

                    b.Property<int?>("FK_NFT_Id")
                        .HasColumnType("integer");

                    b.Property<string>("Image")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "image");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.HasKey("Id");

                    b.ToTable("NftMetadata");

                    b.HasAnnotation("Relational:JsonPropertyName", "metadata");
                });

            modelBuilder.Entity("System_NFT_Token", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "address");

                    b.Property<string>("CirculatingMarketCap")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "circulating_market_cap");

                    b.Property<string>("Decimals")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "decimals");

                    b.Property<string>("ExchangeRate")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "exchange_rate");

                    b.Property<int?>("FK_NFT_Id")
                        .HasColumnType("integer");

                    b.Property<string>("Holders")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "holders");

                    b.Property<string>("IconUrl")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "icon_url");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<string>("Symbol")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "symbol");

                    b.Property<string>("TotalSupply")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "total_supply");

                    b.Property<string>("Type")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "type");

                    b.Property<string>("Volume24h")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "volume_24h");

                    b.HasKey("Id");

                    b.ToTable("NftToken");

                    b.HasAnnotation("Relational:JsonPropertyName", "token");
                });

            modelBuilder.Entity("System_NFT_Attribute", b =>
                {
                    b.HasOne("System_NFT_Metadata", null)
                        .WithMany("Attributes")
                        .HasForeignKey("System_NFT_MetadataId");
                });

            modelBuilder.Entity("System_NFT_Item", b =>
                {
                    b.HasOne("System_NFT_Metadata", "Metadata")
                        .WithMany()
                        .HasForeignKey("MetadataId");

                    b.HasOne("System_NFT_Token", "Token")
                        .WithMany()
                        .HasForeignKey("TokenId");

                    b.Navigation("Metadata");

                    b.Navigation("Token");
                });

            modelBuilder.Entity("System_NFT_Metadata", b =>
                {
                    b.Navigation("Attributes");
                });
#pragma warning restore 612, 618
        }
    }
}
