// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ShibAPI.Migrations.LD_ApplicationDb
{
    [DbContext(typeof(LD_ApplicationDbContext))]
    [Migration("20240827145119_LDv2")]
    partial class LDv2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LDGameSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("timestamptz");

                    b.Property<int>("Map_Id")
                        .HasColumnType("integer");

                    b.Property<int>("Nbr_of_laps")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("LD_GameSession");
                });

            modelBuilder.Entity("LDPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan?>("AI_time_Played")
                        .HasColumnType("interval");

                    b.Property<int?>("Coins")
                        .HasColumnType("integer");

                    b.Property<TimeSpan?>("Custom_time_Played")
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("DogClass1_time_Played")
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("DogClass2_time_Played")
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("DogClass3_time_Played")
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("DogClass4_time_Played")
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("Host_time_Played")
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("Join_time_Played")
                        .HasColumnType("interval");

                    b.Property<int?>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<TimeSpan?>("Total_time_Played")
                        .HasColumnType("interval");

                    b.Property<int?>("User_Id")
                        .HasColumnType("integer");

                    b.Property<int?>("XP")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("LD_Player");
                });

            modelBuilder.Entity("LDPlayerSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Dog_Class")
                        .HasColumnType("integer");

                    b.Property<int>("Game_id")
                        .HasColumnType("integer");

                    b.Property<int>("Player_Id")
                        .HasColumnType("integer");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("interval");

                    b.Property<int>("Xp")
                        .HasColumnType("integer");

                    b.Property<int>("coin")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("LD_PlayerSession");
                });

            modelBuilder.Entity("LDPlayerStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan?>("Best_record")
                        .HasColumnType("interval");

                    b.Property<int?>("Deaths_In_Games")
                        .HasColumnType("integer");

                    b.Property<int?>("Game_Finish_Top3")
                        .HasColumnType("integer");

                    b.Property<int?>("Player_Id")
                        .HasColumnType("integer");

                    b.Property<TimeSpan?>("Time_Played")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.ToTable("LD_PlayerStats");
                });
#pragma warning restore 612, 618
        }
    }
}
