// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ShibAPI.Migrations.MV_ApplicationDb
{
    [DbContext(typeof(MV_ApplicationDbContext))]
    partial class MV_ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MVBids", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int?>("FK_land_Id")
                        .HasColumnType("integer");

                    b.Property<int?>("MVLandsid")
                        .HasColumnType("integer");

                    b.Property<string>("bidBy")
                        .HasColumnType("text");

                    b.Property<decimal?>("bidPrice")
                        .HasColumnType("numeric");

                    b.Property<int?>("block_number")
                        .HasColumnType("integer");

                    b.Property<bool?>("confirmed")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("createdAt")
                        .HasColumnType("timestamptz");

                    b.Property<long?>("landId")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("MVLandsid");

                    b.ToTable("MV_Land_Bids");
                });

            modelBuilder.Entity("MVLands", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<long?>("Land_id")
                        .HasColumnType("bigint")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<bool?>("NoBillAllowedOnLand")
                        .HasColumnType("boolean");

                    b.Property<string>("_id")
                        .HasColumnType("text");

                    b.Property<int?>("bidCount")
                        .HasColumnType("integer");

                    b.Property<string>("currentBidWinner")
                        .HasColumnType("text");

                    b.Property<string>("currentMintWinner")
                        .HasColumnType("text");

                    b.Property<string>("district")
                        .HasColumnType("text");

                    b.Property<string>("hubName")
                        .HasColumnType("text");

                    b.Property<bool?>("intersection")
                        .HasColumnType("boolean");

                    b.Property<bool?>("isRoad")
                        .HasColumnType("boolean");

                    b.Property<bool?>("isShiboshiZone")
                        .HasColumnType("boolean");

                    b.Property<bool?>("minted")
                        .HasColumnType("boolean");

                    b.Property<string>("owner")
                        .HasColumnType("text");

                    b.Property<decimal?>("price")
                        .HasColumnType("numeric");

                    b.Property<string>("primaryRoadName")
                        .HasColumnType("text");

                    b.Property<bool?>("reserved")
                        .HasColumnType("boolean");

                    b.Property<string>("secondaryRoadName")
                        .HasColumnType("text");

                    b.Property<string>("tierName")
                        .HasColumnType("text");

                    b.Property<int?>("x")
                        .HasColumnType("integer");

                    b.Property<int?>("y")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("MV_Lands");
                });

            modelBuilder.Entity("MVMints", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int?>("FK_land_Id")
                        .HasColumnType("integer");

                    b.Property<int?>("MVLandsid")
                        .HasColumnType("integer");

                    b.Property<int?>("block_number")
                        .HasColumnType("integer");

                    b.Property<bool?>("confirmed")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("createdAt")
                        .HasColumnType("timestamptz");

                    b.Property<long?>("landId")
                        .HasColumnType("bigint");

                    b.Property<string>("mintBy")
                        .HasColumnType("text");

                    b.Property<decimal?>("mintPrice")
                        .HasColumnType("numeric");

                    b.HasKey("id");

                    b.HasIndex("MVLandsid");

                    b.ToTable("MV_Land_Mints");
                });

            modelBuilder.Entity("MVBids", b =>
                {
                    b.HasOne("MVLands", null)
                        .WithMany("bids")
                        .HasForeignKey("MVLandsid");
                });

            modelBuilder.Entity("MVMints", b =>
                {
                    b.HasOne("MVLands", null)
                        .WithMany("mints")
                        .HasForeignKey("MVLandsid");
                });

            modelBuilder.Entity("MVLands", b =>
                {
                    b.Navigation("bids");

                    b.Navigation("mints");
                });
#pragma warning restore 612, 618
        }
    }
}
